### ISSUE TITLE
Should we add versions/checksums for maglev

### ISSUE THREAD

**Issue by postmodern** [postmodern/ruby-versions#14]
MagLev hasn't been updated in a while, but the maintainers are [talking about Open Sourcing some of it's internals](https://groups.google.com/forum/m/#!topic/maglev-discussion/CADHEkDx-gA)?

/cc @havenwood @mpapis

**Comment by havenwood** [comment]
I think dropping support for MagLev in ruby-install is a good idea at this point. I'm not sure if we should remove it from ruby-versions or not.

**Comment by postmodern** [comment]
Seeing as how http://glass-downloads.gemstone.com/maglev is no more, I think it's safe to remove MagLev from ruby-versions as well. The information and checksums will live on in the Git history. We could add a tag named `eol-maglev` pointing to the last commit.

**Comment by havenwood** [comment]
Closed by a562e79e73c671a7f06c478adf57d54fb4ebe9a7.
