### ISSUE TITLE
ruby 1.8.7-p375 missing

### ISSUE THREAD

**Issue by ream88** [postmodern/ruby-versions#21]
Any specific reason ruby 1.8.7-p375 is missing?

**Comment by postmodern** [comment]
It's listed in [ruby/versions.txt](https://github.com/postmodern/ruby-versions/blob/36a073cd5883d6db2be37150951f763b9d7e59d1/ruby/versions.txt#L16) but not in `ruby/stable.txt` since 1.8 has been EoLed for a while now and requires older versions of gcc, readline, openssl, etc.

**Comment by havenwood** [comment]
@haihappen It seems like ruby-1.8.7-p375 wasn't ever officially tagged and released so it doesn't show up on the [official mirror](https://cache.ruby-lang.org/pub/ruby/1.8/), it's just in svn.

**Comment by postmodern** [comment]
Oops, I misread that as p357, not p375.

**Comment by sherika36** [comment]
So whats going on with the ruby-1.8.7-p375 .?????....

**Comment by postmodern** [comment]
Closing this since the version never got released to https://cache.ruby-lang.org/pub/ruby/1.8/.
