### ISSUE TITLE
Loop detected

### ISSUE THREAD

**Issue by markovanderpuil** [postmodern/ruby-versions#26]
I get this error for several files in this repo:

`Loop detected on cache-ams4120-AMS: TuFMEtJVICCO9h0Zpde/N9L9b7tugV9xeSSEt9M0!AMS!cache-ams4120-AMS`

**Comment by postmodern** [comment]
How are you getting this error? What is AMS?

**Comment by markovanderpuil** [comment]
1. AMS is probably Amsterdam
2. This turns out to be an issue with GitHub caching servers.
3. My apologies for not closing it earlier.
